# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160909_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
